name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"             # IMPORTANT: 'upload' skips the build step
          app_location: "/"            # folder where your static files live (root here)
          api_location: ""             # no API folder
          output_location: "/"         # where your site files are located (root here)
